In [2]:
import numpy as np

In [3]:
# 0으로 가득찬 배열
arr = np.zeros((2,2))
print(arr)

[[0. 0.]
 [0. 0.]]


In [5]:
arr = np.array([1,2,3,4]).reshape((4,1))
print(arr);print(type(arr))

[[1]
 [2]
 [3]
 [4]]
<class 'numpy.ndarray'>


In [6]:
# 빈 값으로 만들어진 배열
arr = np.empty((3,3))
print(arr)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [9.34609111e-307 1.42413555e-306 1.78019082e-306]
 [1.37959740e-306 2.29178686e-312 1.01436703e-311]]


In [7]:
# 1로 가득찬 배열
arr = np.ones((4,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
print(np.arange(10).reshape((5,2)))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
# ndarray 배열의 모양,차수,데이터 타입 확인
arr = np.array([[1,2,3],[4,5,6]])
print(arr);print(arr.shape);print(arr.ndim);print(arr.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


In [17]:
# 배열의 데이터 타입 바꾸기
arr = arr.astype(np.float64)
print(arr.dtype)

float64


In [18]:
# ndarray 배열의 연산
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr1+arr2

array([[ 6,  8],
       [10, 12]])

In [19]:
arr1*arr2

array([[ 5, 12],
       [21, 32]])

In [20]:
arr1@arr2

array([[19, 22],
       [43, 50]])

In [21]:
arr = np.arange(9).reshape((3,3))
arr_1 = arr[:2,:1]
print(arr_1)

[[0]
 [3]]


In [22]:
idx = arr>3
print(idx)

[[False False False]
 [False  True  True]
 [ True  True  True]]


In [23]:
print(arr[idx])

[4 5 6 7 8]


In [31]:
redwine = np.loadtxt(fname='winequality-red.csv',delimiter=';',skiprows=1)
redwine

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [45]:
redwine.shape

(1599, 12)

In [43]:
print(redwine.std(),redwine.sum(),redwine.var(),redwine.mean())

16.031008997477795 152084.78194 256.993249477214 7.926036165311652


In [42]:
print(redwine.sum(axis=0)) #행방향으로 합계산

[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]


In [46]:
redwine[:,0] # 첫 번째 칼럼만 표시

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

In [47]:
redwine[:,0].sum()

13303.1